### ISSUE TITLE
Error (Cromwell): Failed to evaluate input 'fastqs_R1' and 'fastqs_R2'

### ISSUE THREAD

**Issue by firdaaminy** [ENCODE-DCC/rna-seq-pipeline#47]
Hello.

I'm a new user of this pipeline. Before this, I don't have any experience using Cromwell. Therefore I hope for your understanding regarding this problem that I encountered.

So I ran the RNA-seq pipeline using GCP and Cromwell. The first time I ran it was 1 month ago before you changed the tutorial into the CAPER-CROO method. 1 month ago, I successfully ran the pipeline using Cromwell after some trials and errors and generated the same results as mentioned in the tutorial. Then when I tried to run the pipeline using a different data set, I noticed that the tutorial had changed, from using Cromwell to using Caper-Croo. I tried following the new tutorial using Caper-Croo, however, I encountered some error as well:
`[Caper] Validating WDL/input JSON with womtool... WARNING: Unexpected input provided: rna.aligner [Caper] Error (womtool): WDL or input JSON is invalid.`

I decided to run the pipeline again using Cromwell, however, I re-git cloned the RNA-seq pipeline (I don't know whether or not this has anything to do with this recent Cromwell error). While running the pipeline via Java:

`$ java -jar -Dconfig.file=backends/backend.conf -Dbackend.default=google -Dbackend.providers.google.config.project=rnaseqpipeline-254506 -Dbackend.providers.google.config.root=gs://rna_caper/output Cromwell-38.jar run rna-seq-pipeline.wdl -i input.json -o workflow_opts/docker.json`

I got the following error:

`[error] WorkflowManagerActor Workflow 6ebacece-774c-4088-a01b-c53c99096bab failed (during MaterializingWorkflowDescriptorState): cromwell.engine.workflow.lifecycle.materialization.MaterializeWorkflowDescriptorActor$$anon$1: Workflow input processing failed:
Failed to evaluate input 'fastqs_R1' (reason 1 of 1): No coercion defined from '"gs://rna_seq_output/inputs/ENCSR653DFZ_rep1_chr19_10000reads_R1.fastq.gz"' of type 'spray.json.JsString' to 'Array[File]'.
Failed to evaluate input 'fastqs_R2' (reason 1 of 1): No coercion defined from '"gs://rna_seq_output/inputs/ENCSR653DFZ_rep1_chr19_10000reads_R2.fastq.gz"' of type 'spray.json.JsString' to 'Array[File]'.`

I tried to re-curl and re-copy the indexes and data into the cloud, but still, it generated the same error over and over again after I ran it multiple times.

What could be the possible issue here causing that error? Please, if you don't mind, I would appreciate it if you could help me solve these errors.

Thank you very much for your consideration and your help

**Comment by ottojolanki** [comment]
The first error is my fault, the input in the howto was not correct, it is fixed now. You should try again with caper. I am not maintaining everything in the `backend.conf` except on the parts that I need for some internal testing, and it should not be trusted to work with newest developments in the cloud platforms.

**Comment by leepc12** [comment]
@firdaaminy : Please stick to the Caper method. `backends/backend.conf` was designed for old Cromwell JARs and it is not maintained anymore.

**Comment by firdaaminy** [comment]
Hi again, 
Thank you for your thorough answer

I fixed the input.json according to the newest modification, here's my input.json file:
`{
    "rna.endedness" : "paired",
    "rna.fastqs_R1" : [["gs://rna_caper/inputs/ENCSR653DFZ_rep1_chr19_10000reads_R1.fastq.gz"], ["gs://rna_caper/inputs/ENCSR653DFZ_rep2_chr19_10000reads_R1.fastq.gz"]],
    "rna.fastqs_R2" : [["gs://rna_caper/inputs/ENCSR653DFZ_rep1_chr19_10000reads_R2.fastq.gz"], ["gs://rna_caper/inputs/ENCSR653DFZ_rep2_chr19_10000reads_R2.fastq.gz"]],
    "rna.align_index" : "gs://rna_caper/reference/GRCh38_v24_ERCC_phiX_starIndex_chr19only.tgz",
    "rna.rsem_index" : "gs://rna_caper/reference/GRCh38_v24_ERCC_phiX_rsemIndex_chr19only.tgz",
    "rna.kallisto_index" : "gs://rna_caper/reference/Homo_sapiens.GRCh38.cdna.all.chr19_ERCC_phix_k31_kallisto.idx",
    "rna.bamroot" : "PE_stranded",
    "rna.strandedness" : "stranded",
    "rna.strandedness_direction" : "reverse",
    "rna.chrom_sizes" : "gs://rna_caper/reference/GRCh38_EBV.chrom.sizes",
    "rna.align_ncpus" : 2,
    "rna.align_ramGB" : 4,
    "rna.rsem_ncpus" : 2,
    "rna.rsem_ramGB" : 4,
    "rna.kallisto_number_of_threads" : 2,
    "rna.kallisto_ramGB" : 4,
    "rna.rna_qc_tr_id_to_gene_type_tsv" : "gs://rna_caper/reference/gencodeV24pri-tRNAs-ERCC-phiX.transcript_id_to_genes.tsv",
    "rna.bam_to_signals_ncpus" : 1,
    "rna.bam_to_signals_ramGB" : 2,
    "rna.align_disk" : "local-disk 20 HDD",
    "rna.kallisto_disk" : "local-disk 20 HDD",
    "rna.rna_qc_disk" : "local-disk 20 HDD",
    "rna.bam_to_signals_disk" : "local-disk 20 HDD",
    "rna.mad_qc_disk" : "local-disk 20 HDD",
    "rna.rsem_disk" : "local-disk 20 HDD"
}`

where `rna_caper` is my bucket

Before running the pipeline, I tried to submit the workflow following the tutorial from your page of https://github.com/ENCODE-DCC/caper/blob/master/docs/conf_encode_workshop_2019.md
However, I encountered the same error message:
`[Caper] Error (womtool): WDL or input JSON is invalid.`

Then I directly ran the pipeline without submitting the workflow using the Caper command:
`caper run rna-seq-pipeline.wdl -i input.json -m testrun_metadata.json --docker`
Yet again I'm faced with the same error message as before:
`[Caper] Error (womtool): WDL or input JSON is invalid.`

I compared both the JSON file and the WDL file with your GitHub docs, but I don't see any difference. Is there anything that you could think of that might affect this error? I'm sorry for the inconvenience but I don't see any other way except consulting to you guys. Thank you for your reply and your understanding

**Comment by firdaaminy** [comment]
Since I use GCP to run this pipeline, is it imperative for me to set up a Caper server instance by following this tutorial https://github.com/ENCODE-DCC/caper/blob/master/docs/conf_encode_workshop_2019.md ?

Is there any step from that tutorial that you think may contribute to the error I encountered? Like maybe there's a step that's a little bit tricky and I need to pay more attention to?

**Comment by firdaaminy** [comment]
I've tried multiple times to re-clone the ran-seq-pipeline and rewrite the input.json. I also reinstalled the caper and java according to the tutorial. However, I still get the same error message over and over again. I was wondering, is there any step that I should pay more attention to since it's a little bit tricky? Or is there any step that mostly contributes to this reoccurring error? Should I manually rewrite the rna-seq-pipeline.wdl?

**Comment by ottojolanki** [comment]
I really need to be able to reproduce the error to be able to help you. Could you let me know the following: what does `python3 --version` output (you need => 3.4.2), what does `java -version` output (you need => 1.8), output of `caper -v`. Really this seems to be some problem with the `input.json` because the workflow itself is valid. Maybe you could put the exact file you are using online somewhere so that i could download and inspect it?

**Comment by ottojolanki** [comment]
Another thing that would be helpful: please get the womtool version caper is running from https://github.com/broadinstitute/cromwell/releases, and see what happens when you run `java -jar <womtool jar file> validate <rna seq wdl file> --inputs <your input json>`.

**Comment by ottojolanki** [comment]
Also it looks like older caper version had a bug regarding the validation https://github.com/ENCODE-DCC/caper/releases/tag/v0.5.5 If running an old version, please update caper by running `pip install --upgrade caper`, and restart your caper server.

**Comment by firdaaminy** [comment]
Hi, sorry for the late reply. Thank you so much for your thorough explanation.
So I tried to upgrade my caper but it generated an error message that said "could not find a version that satisfies the requirement caper. No matching distribution found for caper"

Anyhow, I'm running on java version 1.11, my caper is the version of 0.5.4, and I have python3 version 3.7.3. So I believe they are the adequate versions?
And I put my input.json file online so that you could inspect it https://storage.cloud.google.com/rna_caper/input.json?cloudshell=false. My buckets are public so everything could be accessed.

I'm still trying to run the pipeline with the caper, by reinstalling my instance as well. I hope the new caper version will help. Thank you very much for your constant help

**Comment by firdaaminy** [comment]
Also, my caper runs on womtool-42.jar, and when I run the 
```java -jar womtool-42.jar v
alidate rna-seq-pipeline.wdl --inputs input.json```
the output says: success

**Comment by firdaaminy** [comment]
So I'm running the pipeline and the caper server in my mounted disk. I installed the cromwell, caper, java, python in my instance home directory. Everytime I ran the pipeline, I had to write `sudo caper submit rna-seq-pipeline.wdl -i input.json `

because if I don't, then the output will be 
`FileNotFoundError: [Errno 2] No such file or directory: '/home/marufirda/.caper/womtool_jar/womtool-42.jar.lock'`
eventhough I also installed the cromwell-42 and womtool-42 inside my mounted disk.

Does running the pipeline on the mounted disk have anything to do with the error I encounter?

Thank you

**Comment by leepc12** [comment]
Check your Caper version with `caper -v` and check if it's >=0.6.1. The latest Caper uses cromwell/womtool 47.

Don't `sudo` for caper commands.

**Comment by firdaaminy** [comment]
No it is not. My caper version is 0.5.4 and when I tried to upgrade it using the `pip install --upgrade caper` command, it didn't work, the output said:
`could not find a version that satisfies the requirement caper. No matching distribution found for caper`

**Comment by leepc12** [comment]
Please try `pip uninstall caper` and then re-install `pip install caper==0.6.1`.

**Comment by firdaaminy** [comment]
Finally solve this issue by reinstalling my instance and downloading the newest caper, Cromwell, and Womtool. Thank you very much for all of your thorough answers and constant help
